Repository DSoftofficial/Tilder-web-app, pull requests merged in 2023-12, with the labels that each got.

#25 Updated MenuBar and SideBar
  web-app/index.html
  web-app/package-lock.json
  web-app/src/App.css
  web-app/src/App.jsx
  web-app/src/components/MenuBar/MenuBar.jsx
  web-app/src/components/SideBar/Main Components/Debug/Debug.jsx
  web-app/src/components/SideBar/Main Components/filePioneer/filePioneer.jsx
  web-app/src/components/SideBar/SideBar.jsx
  web-app/vite.config.js
Labels: enhancement, good first issue, important, required

#26 Added the functionality to toggle SideBar icons & MonacoEditor
  .github/dependabot.yml
  web-app/index.html
  web-app/package-lock.json
  web-app/package.json
  web-app/src/App.css
  web-app/src/App.jsx
  web-app/src/components/Editor/MonacoEditor.jsx
  web-app/src/components/MenuBar/MenuBar.jsx
  web-app/src/components/SideBar/Main Components/filePioneer/filePioneer.jsx
  web-app/src/components/SideBar/SideBar.jsx
Labels: enhancement, good first issue, important, required, dependencies

#29 Updated the Toggling feature of the `ariaExpanded`
  web-app/src/App.css
  web-app/src/App.jsx
  web-app/src/components/Editor/MonacoEditor.jsx
  web-app/src/components/SideBar/Main Components/GItHub/GitHub.jsx
  web-app/src/components/SideBar/Main Components/Search/Search.jsx
  web-app/src/components/SideBar/Main Components/filePioneer/filePioneer.jsx
  web-app/src/components/SideBar/SideBar.jsx
Labels: enhancement, good first issue, important, required

#30 Updated the Toggling feature
  web-app/src/App.css
  web-app/src/App.jsx
  web-app/src/components/MenuBar/MenuBar.jsx
  web-app/src/components/SideBar/Main Components/Code Blocks/CodeBlocks.jsx
  web-app/src/components/SideBar/Main Components/Debug/Debug.jsx
  web-app/src/components/SideBar/Main Components/Extensions/Extensions.jsx
  web-app/src/components/SideBar/Main Components/GItHub/GitHub.jsx
  web-app/src/components/SideBar/Main Components/Git/Git.jsx
  web-app/src/components/SideBar/Main Components/Search/Search.jsx
  web-app/src/components/SideBar/Main Components/Terminal/Terminal.jsx
  web-app/src/components/SideBar/Main Components/filePioneer/filePioneer.jsx
  web-app/src/components/SideBar/SideBar.jsx
Labels: enhancement, good first issue, important, required

#31 Added the Welcome Page
  .github/workflows/deploy.yml
  README.md
  web-app/package-lock.json
  web-app/package.json
  web-app/src/App.css
  web-app/src/App.jsx
  web-app/src/components/Editor/MonacoEditor.jsx
  web-app/src/components/Tabs/Tabs.jsx
Labels: enhancement, good first issue
